name: Add contributors
on:
#  schedule:
#    - cron:  '20 20 * * *'
  push:
    branches:
      - master
      - gh-pages

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: baileythegreen/add-contributors@patch-1
      with:
        REPO_NAME: 'baileythegreen/glosario'
        CONTRIBUTOR: '<!--Contributors-->'
        COLUMN_PER_ROW: '4'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '90'
        FONT_SIZE: '14'
        PATH: '/CONTRIBUTORS.html'
        COMMIT_MESSAGE: 'docs(CONTRIBUTORS): update contributors'
        AVATAR_SHAPE: 'round'
